### PR TITLE
chore: browser example

### PR DESCRIPTION
**Pull request by obecny**

### CODE REVIEW

**Comment by mwear** [comment]
@obecny: I was wondering if we can make the README point to the version on the Lightstep website: https://docs.lightstep.com/otel/js-getting-started-with-opentelemetry. It would still be nice to have the content as markdown in the repo, but maybe we can just call it, content.md so it's not the main page people will see in that folder.

Also, the .gitignore has a conflict we should resolve.

**Comment by obecny** [comment]
I would call it `getting-started.md`. Any proposition how would the readme look like then ?

**Comment by mwear** [comment]
Something like:

## Getting Started with OpenTelemetry

This repo contains the source code that accompanies the [browser getting started guide](https://docs.lightstep.com/otel/js-getting-started-with-opentelemetry) on the [Lightstep Learning Portal](https://docs.lightstep.com/otel/what-is-opentelemetry). Visit [the portal](https://docs.lightstep.com/otel/what-is-opentelemetry) for this and other great resources on OpenTelemetry.

**Comment by obecny** [comment]
@mwear done

**Pull request merged**
