### PR TITLE
added otel collector kafka demo

### PR DESCRIPTION
**Pull request by hecomp**
What does this PR do?
---------------------
Add otel collector kafka demo

Why are you doing it?
---------------------

What are you asking the reviewer to do?
---------------------
If "review", leave off.

How can the reviewer test/see/play with the changes?
---------------------
If "run tests", leave off.

***
R/CC: _Who should know about this change?

### CODE REVIEW

**Review by nslaughter — COMMENTED** [review]
I'm really happy about this addition to the examples and I like the way it looks. But I don't see a consumer service in the config. Wondering how that fits in.

**Comment by hecomp** [comment]
> I'm really happy about this addition to the examples and I like the way it looks. But I don't see a consumer service in the config. Wondering how that fits in.

Yeah, thanks, I've also follow the receiver config doc to set up the receiver. https://github.com/lightstep/opentelemetry-collector-contrib/blob/main/receiver/kafkametricsreceiver/README.md

**Comment by nslaughter** [comment]
> Oh way the consumer is in the same service together with the producer.

That setup works fine - especially for our use. I just think we should update the service name so that people so that it has 2 roles. 

Alternatively we could run a consumer process in one service and producer in another.

**Comment by hecomp** [comment]
> > Oh way the consumer is in the same service together with the producer.
> 
> That setup works fine - especially for our use. I just think we should update the service name so that people so that it has 2 roles.
> 
> Alternatively we could run a consumer process in one service and producer in another.

Refactor to run producer and consumer in seperate services.

**Pull request merged**
