### PR TITLE
Added cassandra metrics addition

### PR DESCRIPTION
**Pull request by hecomp**
Cassandra Example for metrics addition

### CODE REVIEW

**Comment by carlosalberto** [comment]
Cannot run this one, getting:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cassandra: 'interval'
services.cassandra.healthcheck contains an invalid type, it should be an object
```

**Comment by hecomp** [comment]
> Cannot run this one, getting:
> 
> ```
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for services.cassandra: 'interval'
> services.cassandra.healthcheck contains an invalid type, it should be an object
> ```



> Cannot run this one, getting:
> 
> ```
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for services.cassandra: 'interval'
> services.cassandra.healthcheck contains an invalid type, it should be an object
> ```

@carlosalberto will fix.

**Comment by hecomp** [comment]
> Cannot run this one, getting:
> 
> ```
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for services.cassandra: 'interval'
> services.cassandra.healthcheck contains an invalid type, it should be an object
> ```

@carlosalberto fixed. My IDE changed the indentation.

**Review by codeboten — COMMENTED** [review]
Tested this as well

**Pull request merged**
